services:
  iam-service:
    build:
      target: development
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    environment:
      - NODE_ENV=development
